#pragma once

#define SHUNYA_MOUSE_BUTTON_1         0
#define SHUNYA_MOUSE_BUTTON_2         1
#define SHUNYA_MOUSE_BUTTON_3         2
#define SHUNYA_MOUSE_BUTTON_4         3
#define SHUNYA_MOUSE_BUTTON_5         4
#define SHUNYA_MOUSE_BUTTON_6         5
#define SHUNYA_MOUSE_BUTTON_7         6
#define SHUNYA_MOUSE_BUTTON_8         7
#define SHUNYA_MOUSE_BUTTON_LAST      SHUNYA_MOUSE_BUTTON_8
#define SHUNYA_MOUSE_BUTTON_LEFT      SHUNYA_MOUSE_BUTTON_1
#define SHUNYA_MOUSE_BUTTON_RIGHT     SHUNYA_MOUSE_BUTTON_2
#define SHUNYA_MOUSE_BUTTON_MIDDLE    SHUNYA_MOUSE_BUTTON_3
